version: '3.8'

networks:
  quotation-network:
    driver: bridge

services:
  quotation-job:
    build:
      context: .
      dockerfile: ./Dockerfile.job
    volumes:
      - .:/app
    depends_on:
      - quotation-redis
    links:
      - quotation-redis
    networks:
      - quotation-network

  quotation-redis:
    image: bitnami/redis:latest
    user: root
    container_name: quotation-redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    environment:
      - ALLOW_EMPTY_PASSWORD=${REDIS_ALLOW_EMPTY_PASSWORD}
      - REDIS_REPLICATION_MODE=${REDIS_REPLICATION_MODE}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./redis:/bitnami
    networks:
      - quotation-network
