FROM golang:1.15-alpine

RUN apk add --update git
RUN go get github.com/gocraft/work/cmd/workwebui && \
  go install github.com/gocraft/work/cmd/workwebui

CMD workwebui -redis="$REDIS_HOSTS" -ns="quotation_workspace" -listen="0.0.0.0:8181"
